version: "3.7"
services:
    node:
        build:
            context: react
        ports:
            - "3000:3000"
        volumes:
            - ./react/src:/app/src:ro
        env_file:
            - ./react/.env
