version: "3.7"
services:
    node:
        build:
            context: react
        ports:
            - "8080:8080"
        volumes:
            - ./react/src:/app/src:ro
        env_file:
            - ./react/.env

    app:
        build:
            args:
                user: dan
                uid: 10001
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - mynetwork

    #Nginx Service
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./Docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - mynetwork
    #Mysl Service
    db:
        image: mysql:8
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        networks:
            - mynetwork

networks:
    mynetwork:
        driver: bridge
