version: "3.7"
services:
    node:
        build:
            context: .
        ports:
            - "8080:8080"
        volumes:
            - ./src:/app/src:ro
        env_file:
            - ./.env
