FROM node:18-alpine as react-build

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx
COPY --from=react-build /app /usr/share/nginx/html
